version: '3.2'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.devcontainer/traefik/:/etc/traefik/
    environment:
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_FILE=true
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik/
    depends_on:
      - devcontainer

  devcontainer:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    image: users/devcontainer:latest
    working_dir: /users
    tty: true
    user: vscode:vscode
    shm_size: "4gb"
    volumes:
      - ./:/users/
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/vscode/.ssh
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=true"

      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.apps.entrypoints=websecure"
      - "traefik.http.routers.app.rule=Host(`dev.opticaspaco.pt`)"
      - "traefik.http.routers.apps.rule=Host(`dev.opticaspaco.pt`)"
      - "traefik.http.routers.app.middlewares=redirect"
      - "traefik.http.routers.apps.tls=true"
      - "traefik.http.routers.app.service=www"
      - "traefik.http.routers.apps.service=www"
      - "traefik.http.services.www.loadbalancer.server.port=4444"
  
  database:
    image: postgres:15
    env_file: .env
